<a href="https://colab.research.google.com/github/maniero1980/Demo-repo/blob/master/numpyINCLASS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [53]:
import numpy as np

In [54]:
number_list = [5,9,15,25,40]
number_list

[5, 9, 15, 25, 40]

In [55]:
np.array(number_list)

array([ 5,  9, 15, 25, 40])

In [56]:
number_array = np.array(number_list)

In [57]:
number_array/3

array([ 1.66666667,  3.        ,  5.        ,  8.33333333, 13.33333333])

In [58]:
number_array % 3

array([2, 0, 0, 1, 1])

In [59]:
new_list = []
for x in number_list:
  y = x/3
  new_list.append(y)
new_list

[1.6666666666666667, 3.0, 5.0, 8.333333333333334, 13.333333333333334]

In [60]:
number_array.reshape(-1,1)

array([[ 5],
       [ 9],
       [15],
       [25],
       [40]])

In [61]:
df = np.array([[1,2,3], [4,5,6]])

In [62]:
import pandas as pd
pd.DataFrame(df)

0  1  2
0  1  2  3
1  4  5  6

In [25]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [28]:
np.arange(0,101,5)

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

In [34]:
np.random.random()

0.12567067121483977

In [40]:
np.random.seed(123)
np.random.random()

0.6964691855978616

In [45]:
np.random.random()*10

4.23106460124461

In [46]:
number_array

array([ 5,  9, 15, 25, 40])

In [63]:
number_array.argmin()

0

In [64]:
number_array[0]

5

In [65]:
number_array.argmax()

4

In [66]:
number_array[4]

40

In [67]:
number_array

array([ 5,  9, 15, 25, 40])

In [70]:
np.where(number_array > 12, 'big', 'small')

array(['small', 'small', 'big', 'big', 'big'], dtype='<U5')

In [72]:
import pandas as pd
df = pd.read_csv('titanic.csv')

In [73]:
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [74]:
np.where(df['Age']> 50, 'old','young')

array(['young', 'young', 'young', 'young', 'young', 'young', 'old',
       'young', 'young', 'young', 'young', 'old', 'young', 'young',
       'young', 'old', 'young', 'young', 'young', 'young', 'young',
       'young', 'young', 'young', 'young', 'young', 'young', 'young',
       'young', 'young', 'young', 'young', 'young', 'old', 'young',
       'young', 'young', 'young', 'young', 'young', 'young', 'young',
       'young', 'young', 'young', 'young', 'young', 'young', 'young',
       'young', 'young', 'young', 'young', 'young', 'old', 'young',
       'young', 'young', 'young', 'young', 'young', 'young', 'young',
       'young', 'young', 'young', 'young', 'young', 'young', 'young',
       'young', 'young', 'young', 'young', 'young', 'young', 'young',
       'young', 'young', 'young', 'young', 'young', 'young', 'young',
       'young', 'young', 'young', 'young', 'young', 'young', 'young',
       'young', 'young', 'young', 'old', 'young', 'old', 'young', 'young',
       'young', 'young', 

In [75]:
np.where(df['Age']> 50, 'old',np.where(df['Age'] > 25, 'middle age', 'young'))

array(['young', 'middle age', 'middle age', 'middle age', 'middle age',
       'young', 'old', 'young', 'middle age', 'young', 'young', 'old',
       'young', 'middle age', 'young', 'old', 'young', 'young',
       'middle age', 'young', 'middle age', 'middle age', 'young',
       'middle age', 'young', 'middle age', 'young', 'young', 'young',
       'young', 'middle age', 'young', 'young', 'old', 'middle age',
       'middle age', 'young', 'young', 'young', 'young', 'middle age',
       'middle age', 'young', 'young', 'young', 'young', 'young', 'young',
       'young', 'young', 'young', 'young', 'middle age', 'middle age',
       'old', 'young', 'young', 'middle age', 'young', 'young', 'young',
       'middle age', 'middle age', 'young', 'young', 'young',
       'middle age', 'young', 'young', 'middle age', 'middle age',
       'young', 'young', 'middle age', 'middle age', 'young', 'young',
       'young', 'young', 'middle age', 'young', 'middle age', 'young',
       'middle age', 'you

In [77]:
df['Age group'] = np.where(df['Age']> 50, 'old',np.where(df['Age'] > 25, 'middle age', 'young'))

In [79]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked   Age group  
0      0         A/5 21171   7.2500   NaN        S       young  
1      0          PC 17599  71.2833   C85        C  middle age  
2      0  STON/O2. 3101282   7.9250   NaN        S  middle age  
3      0            113803  53.1000  C123        S  middle age  
4      0            373450   8.0500   NaN        S  middle age

In [80]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
 12  Age group    891 non-null    object 
dtypes: float64(2), int64(5), object(6)
memory usage: 90.6+ KB


In [82]:
np.mean(number_array)

18.8